{application,squares_of_life,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"squares_of_life"},
              {modules,['Elixir.Entity','Elixir.KV.Supervisor','Elixir.Loop',
                        'Elixir.Randomize','Elixir.SquaresOfLife',gl_const,
                        wx_const]},
              {registered,[]},
              {vsn,"0.1.0"},
              {extra_applications,[logger]}]}.
